### ISSUE TITLE
Criar o boilerplate básico

### ISSUE THREAD

**Issue by wilcorrea** [phpzm/mentoria#6]
Crie uma pasta que contenha uma pasta chamada `src`, outra chamada `bootstrap` e crie um arquivo composer.json.

Crie em bootstrap um arquivo chamado index.php e configure o autoload do composer usando a propriedade file para carregar esse arquivo.

Adicione também uma entrada de PSR-4 a propriedade autoload do composer e configure um namespace de sua escolha para carregar as classes da pasta src

**Comment by Belluzzo** [comment]
A criação desse projeto foi transferida para outro repositório. 

https://github.com/phpzm/appanel
